name: "VideoMaker"
 
on: workflow_dispatch

jobs:
  videomaker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing unzip
        run: brew install unzip
      - name: Unzipping the video.zip file
        run: unzip video.zip -d tmpfolder20220805
      - name: Checking if a VideoMaker configuration exists
        run: |
             if [ $(wc -c <"./tmpfolder20220805/video/input_video.cfg") -ge 5 ]
               then
                 echo "VideoMaker configuration file found."
               else
                 echo "VideoMaker configuration file not found."
                 exit 1
             fi
      - name: Installing ffmpeg 
        run: brew install ffmpeg
      - name: Making the VideoMaker script executable
        run: chmod +x ./make.sh
      - name: Creating the video file
        run: cd tmpfolder20220805/video && ../../make.sh && cp output.mp4 created-video.mp4
      - name: Attaching the created video this workflow
        uses: actions/upload-artifact@v2
        with:
          name: created-video
          path: tmpfolder20220805/video/created-video.mp4
